[package]
name = "rogue-like-prototype"
version = "0.1.0"
authors = ["John"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
bevy_egui = "0.4"
bevy_tilemap = { git="https://github.com/StarArawn/bevy_tilemap.git", branch="fix-precision" }
noise = "0.7"
pathfinding = "2.1"
rand = "0.8"